---
 - name: Linux user password security settings
   hosts: all
   become: yes
   tasks:
     - name: Install pam_cracklib package
       package:
          name: "libpam-cracklib"
          state: present

     - name: Configuring password requirements using pam_cracklib
       lineinfile:
          dest: "/etc/pam.d/common-password"
          regexp: "pam_cracklib.so"
          line: "password required pam_cracklib.so try_first_pass retry=3 minlen=8 reject_username enforce_for_root"
          state: present